version: '3'

services:
  mysql:
    image: "mysql-image"
    build: "./sql-db"
    restart: always
    ports:
      - "3306:3306"
    networks: 
     - app-network
  web:
    image: "php-image"
    build: "./phppr"
    restart: always
    ports:
      - "8000:8000"
    networks: 
      - app-network
  
  #Docker networks
networks: 
  app-network:
    driver: bridge

  